mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  profiles:
    include:
#      - configlocal
      - configremote

server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  tomcat:
    uri-encoding: UTF-8