server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#  undertow:
#    decode-url: false
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/war3elo
    username: mysql
    password: mysql
    sql-script-encoding: UTF-8