jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot_test
  username: root
  password: 210113

# tomcat端口
server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/war3elo
    username: root
    password: 210113

mybatis:
  # 实体类别名包路径
#  type-aliases-package: com.lzm.pojo
  # 映射文件路径
#  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
